<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Municipio;

class MunicipioSeeder extends Seeder
{
    public function run(): void
    {
        $municipios = [
            // Amazonas (estado_id = 1)
            ['nombre' => 'Atabapo', 'estado_id' => 1],
            ['nombre' => 'Atures', 'estado_id' => 1],
            ['nombre' => 'Alto Orinoco', 'estado_id' => 1],
            ['nombre' => 'Autana', 'estado_id' => 1],
            ['nombre' => 'Manapiare', 'estado_id' => 1],
            ['nombre' => 'Maroa', 'estado_id' => 1],
            ['nombre' => 'Río Negro', 'estado_id' => 1],

            // Anzoátegui (estado_id = 2)
            ['nombre' => 'Anaco', 'estado_id' => 2],
            ['nombre' => 'Aragua', 'estado_id' => 2],
            ['nombre' => 'Diego Bautista Urbaneja', 'estado_id' => 2], // ¡agregado!
            ['nombre' => 'Fernando de Peñalver', 'estado_id' => 2],
            ['nombre' => 'Francisco de Miranda', 'estado_id' => 2],
            ['nombre' => 'Francisco del Carmen Carvajal', 'estado_id' => 2],
            ['nombre' => 'Guanta', 'estado_id' => 2],
            ['nombre' => 'Independencia', 'estado_id' => 2],
            ['nombre' => 'José Gregorio Monagas', 'estado_id' => 2],
            ['nombre' => 'Juan Antonio Sotillo', 'estado_id' => 2],
            ['nombre' => 'Juan Manuel Cajigal', 'estado_id' => 2],
            ['nombre' => 'Libertad', 'estado_id' => 2],
            ['nombre' => 'Manuel Ezequiel Bruzual', 'estado_id' => 2],
            ['nombre' => 'Pedro María Freites', 'estado_id' => 2],
            ['nombre' => 'Píritu', 'estado_id' => 2],
            ['nombre' => 'San José de Guanipa', 'estado_id' => 2],
            ['nombre' => 'San Juan de Capistrano', 'estado_id' => 2],
            ['nombre' => 'Santa Ana', 'estado_id' => 2],
            ['nombre' => 'Simón Bolívar', 'estado_id' => 2],
            ['nombre' => 'Simón Rodríguez', 'estado_id' => 2],
            ['nombre' => 'Sotillo', 'estado_id' => 2], // a veces es 'Juan Antonio Sotillo' ya cubierto
            // Nota: Si ya incluiste 'Juan Antonio Sotillo', no agregues el duplicado 'Sotillo'.

            // Apure (estado_id = 3)
            ['nombre' => 'Achaguas', 'estado_id' => 3],
            ['nombre' => 'Biruaca', 'estado_id' => 3],
            ['nombre' => 'Muñoz', 'estado_id' => 3],
            ['nombre' => 'Páez', 'estado_id' => 3],
            ['nombre' => 'Pedro Camejo', 'estado_id' => 3],
            ['nombre' => 'Rómulo Gallegos', 'estado_id' => 3],
            ['nombre' => 'San Fernando', 'estado_id' => 3],

            // Aragua (estado_id = 4)
            ['nombre' => 'Bolívar', 'estado_id' => 4],
            ['nombre' => 'Camatagua', 'estado_id' => 4],
            ['nombre' => 'Francisco Linares Alcántara', 'estado_id' => 4],
            ['nombre' => 'Girardot', 'estado_id' => 4],
            ['nombre' => 'José Ángel Lamas', 'estado_id' => 4],
            ['nombre' => 'José Félix Ribas', 'estado_id' => 4],
            ['nombre' => 'José Rafael Revenga', 'estado_id' => 4],
            ['nombre' => 'Libertador', 'estado_id' => 4],
            ['nombre' => 'Mario Briceño Iragorry', 'estado_id' => 4],
            ['nombre' => 'Ocumare de la Costa de Oro', 'estado_id' => 4],
            ['nombre' => 'San Casimiro', 'estado_id' => 4],
            ['nombre' => 'San Sebastián', 'estado_id' => 4],
            ['nombre' => 'Santiago Mariño', 'estado_id' => 4],
            ['nombre' => 'Santos Michelena', 'estado_id' => 4],
            ['nombre' => 'Sucre', 'estado_id' => 4],
            ['nombre' => 'Tovar', 'estado_id' => 4],
            ['nombre' => 'Urdaneta', 'estado_id' => 4],
            ['nombre' => 'Zamora', 'estado_id' => 4],

            // Barinas (estado_id = 5)
            ['nombre' => 'Alberto Arvelo Torrealba', 'estado_id' => 5],
            ['nombre' => 'Andrés Eloy Blanco', 'estado_id' => 5],
            ['nombre' => 'Antonio José de Sucre', 'estado_id' => 5],
            ['nombre' => 'Arismendi', 'estado_id' => 5],
            ['nombre' => 'Barinas', 'estado_id' => 5],
            ['nombre' => 'Bolívar', 'estado_id' => 5],
            ['nombre' => 'Cruz Paredes', 'estado_id' => 5],
            ['nombre' => 'Ezequiel Zamora', 'estado_id' => 5],
            ['nombre' => 'Obispos', 'estado_id' => 5],
            ['nombre' => 'Pedraza', 'estado_id' => 5],
            ['nombre' => 'Rojas', 'estado_id' => 5],
            ['nombre' => 'Sosa', 'estado_id' => 5],
            ['nombre' => 'José Antonio Páez', 'estado_id' => 5], // **agregado faltante**

            // Bolívar (estado_id = 6)
            ['nombre' => 'Caroní', 'estado_id' => 6],
            ['nombre' => 'Cedeño', 'estado_id' => 6],
            ['nombre' => 'El Callao', 'estado_id' => 6],
            ['nombre' => 'Gran Sabana', 'estado_id' => 6],
            ['nombre' => 'Heres', 'estado_id' => 6],
            ['nombre' => 'Piar', 'estado_id' => 6],
            ['nombre' => 'Raúl Leoni', 'estado_id' => 6],
            ['nombre' => 'Roscio', 'estado_id' => 6],
            ['nombre' => 'Sifontes', 'estado_id' => 6],
            ['nombre' => 'Sucre', 'estado_id' => 6],
            ['nombre' => 'Padre Pedro Chien', 'estado_id' => 6],

            // Carabobo (estado_id = 7)
            ['nombre' => 'Bejuma', 'estado_id' => 7],
            ['nombre' => 'Carlos Arvelo', 'estado_id' => 7],
            ['nombre' => 'Diego Ibarra', 'estado_id' => 7],
            ['nombre' => 'Guacara', 'estado_id' => 7],
            ['nombre' => 'Juan José Mora', 'estado_id' => 7],
            ['nombre' => 'Libertador', 'estado_id' => 7],
            ['nombre' => 'Los Guayos', 'estado_id' => 7],
            ['nombre' => 'Miranda', 'estado_id' => 7],
            ['nombre' => 'Montalbán', 'estado_id' => 7],
            ['nombre' => 'Naguanagua', 'estado_id' => 7],
            ['nombre' => 'Puerto Cabello', 'estado_id' => 7],
            ['nombre' => 'San Diego', 'estado_id' => 7],
            ['nombre' => 'San Joaquín', 'estado_id' => 7],
            ['nombre' => 'Valencia', 'estado_id' => 7],

            // Cojedes (estado_id = 8)
            ['nombre' => 'Anzoátegui', 'estado_id' => 8],
            ['nombre' => 'Falcón', 'estado_id' => 8],
            ['nombre' => 'Girardot', 'estado_id' => 8],
            ['nombre' => 'Lima Blanco', 'estado_id' => 8],
            ['nombre' => 'Pao de San Juan Bautista', 'estado_id' => 8],
            ['nombre' => 'Ricaurte', 'estado_id' => 8],
            ['nombre' => 'Rómulo Gallegos', 'estado_id' => 8],
            ['nombre' => 'San Carlos', 'estado_id' => 8],
            ['nombre' => 'Tinaco', 'estado_id' => 8],

            // Delta Amacuro (estado_id = 9)
            ['nombre' => 'Antonio Díaz', 'estado_id' => 9],
            ['nombre' => 'Casacoima', 'estado_id' => 9],
            ['nombre' => 'Pedernales', 'estado_id' => 9],
            ['nombre' => 'Tucupita', 'estado_id' => 9],

            // Distrito Capital (estado_id = 10)
            ['nombre' => 'Libertador', 'estado_id' => 10],

            // Falcón (estado_id = 11)
            ['nombre' => 'Acosta', 'estado_id' => 11],
            ['nombre' => 'Bolívar', 'estado_id' => 11],
            ['nombre' => 'Buchivacoa', 'estado_id' => 11],
            ['nombre' => 'Cacique Manaure', 'estado_id' => 11],
            ['nombre' => 'Carirubana', 'estado_id' => 11],
            ['nombre' => 'Colina', 'estado_id' => 11],
            ['nombre' => 'Dabajuro', 'estado_id' => 11],
            ['nombre' => 'Democracia', 'estado_id' => 11],
            ['nombre' => 'Falcón', 'estado_id' => 11],
            ['nombre' => 'Federación', 'estado_id' => 11],
            ['nombre' => 'Jacura', 'estado_id' => 11],
            ['nombre' => 'Los Taques', 'estado_id' => 11],
            ['nombre' => 'Mauroa', 'estado_id' => 11],
            ['nombre' => 'Miranda', 'estado_id' => 11],
            ['nombre' => 'Monseñor Iturriza', 'estado_id' => 11],
            ['nombre' => 'Palmasola', 'estado_id' => 11],
            ['nombre' => 'Petit', 'estado_id' => 11],
            ['nombre' => 'Píritu', 'estado_id' => 11],
            ['nombre' => 'San Francisco', 'estado_id' => 11],
            ['nombre' => 'Silva', 'estado_id' => 11],
            ['nombre' => 'Sucre', 'estado_id' => 11],
            ['nombre' => 'Tocópero', 'estado_id' => 11],
            ['nombre' => 'Unión', 'estado_id' => 11],
            ['nombre' => 'Urumaco', 'estado_id' => 11],
            ['nombre' => 'Zamora', 'estado_id' => 11],

            // Guárico (estado_id = 12)
            ['nombre' => 'Camaguán', 'estado_id' => 12],
            ['nombre' => 'Chaguaramas', 'estado_id' => 12],
            ['nombre' => 'El Socorro', 'estado_id' => 12],
            ['nombre' => 'Francisco de Miranda', 'estado_id' => 12],
            ['nombre' => 'José Félix Ribas', 'estado_id' => 12],
            ['nombre' => 'José Tadeo Monagas', 'estado_id' => 12],
            ['nombre' => 'Juan Germán Roscio', 'estado_id' => 12],
            ['nombre' => 'Julián Mellado', 'estado_id' => 12],
            ['nombre' => 'Las Mercedes', 'estado_id' => 12],
            ['nombre' => 'Leonardo Infante', 'estado_id' => 12],
            ['nombre' => 'Pedro Zaraza', 'estado_id' => 12],
            ['nombre' => 'Ortíz', 'estado_id' => 12],
            ['nombre' => 'San Gerónimo de Guayabal', 'estado_id' => 12],
            ['nombre' => 'San José de Guaribe', 'estado_id' => 12],
            ['nombre' => 'Santa María de Ipire', 'estado_id' => 12],
            ['nombre' => 'Sebastián Francisco de Miranda', 'estado_id' => 12],

            // Lara (estado_id = 13)
            ['nombre' => 'Andrés Eloy Blanco', 'estado_id' => 13],
            ['nombre' => 'Crespo', 'estado_id' => 13],
            ['nombre' => 'Iribarren', 'estado_id' => 13],
            ['nombre' => 'Jiménez', 'estado_id' => 13],
            ['nombre' => 'Morán', 'estado_id' => 13],
            ['nombre' => 'Palavecino', 'estado_id' => 13],
            ['nombre' => 'Simón Planas', 'estado_id' => 13],
            ['nombre' => 'Torres', 'estado_id' => 13],
            ['nombre' => 'Urdaneta', 'estado_id' => 13],
            // Mérida (estado_id = 14)
            ['nombre' => 'Alberto Adriani', 'estado_id' => 14],
            ['nombre' => 'Andrés Bello', 'estado_id' => 14],
            ['nombre' => 'Antonio Pinto Salinas', 'estado_id' => 14],
            ['nombre' => 'Aricagua', 'estado_id' => 14],
            ['nombre' => 'Arzobispo Chacón', 'estado_id' => 14],
            ['nombre' => 'Campo Elías', 'estado_id' => 14],
            ['nombre' => 'Caracciolo Parra Olmedo', 'estado_id' => 14],
            ['nombre' => 'Cardenal Quintero', 'estado_id' => 14],
            ['nombre' => 'Guaraque', 'estado_id' => 14],
            ['nombre' => 'Julio César Salas', 'estado_id' => 14],
            ['nombre' => 'Justo Briceño', 'estado_id' => 14],
            ['nombre' => 'Libertador', 'estado_id' => 14],
            ['nombre' => 'Miranda', 'estado_id' => 14],
            ['nombre' => 'Obispo Ramos de Lora', 'estado_id' => 14],
            ['nombre' => 'Padre Noguera', 'estado_id' => 14],
            ['nombre' => 'Pueblo Llano', 'estado_id' => 14],
            ['nombre' => 'Rangel', 'estado_id' => 14],
            ['nombre' => 'Rivas Dávila', 'estado_id' => 14],
            ['nombre' => 'Santos Marquina', 'estado_id' => 14],
            ['nombre' => 'Sucre', 'estado_id' => 14],
            ['nombre' => 'Tovar', 'estado_id' => 14],
            ['nombre' => 'Tulio Febres Cordero', 'estado_id' => 14],
            ['nombre' => 'Zea', 'estado_id' => 14],

            // Miranda (estado_id = 15)
            ['nombre' => 'Acevedo', 'estado_id' => 15],
            ['nombre' => 'Andrés Bello', 'estado_id' => 15],
            ['nombre' => 'Baruta', 'estado_id' => 15],
            ['nombre' => 'Brión', 'estado_id' => 15],
            ['nombre' => 'Buroz', 'estado_id' => 15],
            ['nombre' => 'Carrizal', 'estado_id' => 15],
            ['nombre' => 'Chacao', 'estado_id' => 15],
            ['nombre' => 'Cristóbal Rojas', 'estado_id' => 15],
            ['nombre' => 'El Hatillo', 'estado_id' => 15],
            ['nombre' => 'Guaicaipuro', 'estado_id' => 15],
            ['nombre' => 'Independencia', 'estado_id' => 15],
            ['nombre' => 'Lander', 'estado_id' => 15],
            ['nombre' => 'Los Salias', 'estado_id' => 15],
            ['nombre' => 'Páez', 'estado_id' => 15],
            ['nombre' => 'Paz Castillo', 'estado_id' => 15],
            ['nombre' => 'Pedro Gual', 'estado_id' => 15],
            ['nombre' => 'Plaza', 'estado_id' => 15],
            ['nombre' => 'Simón Bolívar', 'estado_id' => 15],
            ['nombre' => 'Sucre', 'estado_id' => 15],
            ['nombre' => 'Urdaneta', 'estado_id' => 15],
            ['nombre' => 'Zamora', 'estado_id' => 15],

            // Monagas (estado_id = 16)
            ['nombre' => 'Acosta', 'estado_id' => 16],
            ['nombre' => 'Aguasay', 'estado_id' => 16],
            ['nombre' => 'Bolívar', 'estado_id' => 16],
            ['nombre' => 'Caripe', 'estado_id' => 16],
            ['nombre' => 'Cedeño', 'estado_id' => 16],
            ['nombre' => 'Ezequiel Zamora', 'estado_id' => 16],
            ['nombre' => 'Libertador', 'estado_id' => 16],
            ['nombre' => 'Maturín', 'estado_id' => 16],
            ['nombre' => 'Piar', 'estado_id' => 16],
            ['nombre' => 'Punceres', 'estado_id' => 16],
            ['nombre' => 'Santa Bárbara', 'estado_id' => 16],
            ['nombre' => 'Sotillo', 'estado_id' => 16],
            ['nombre' => 'Uracoa', 'estado_id' => 16],

            // Nueva Esparta (estado_id = 17)
            ['nombre' => 'Antolín del Campo', 'estado_id' => 17],
            ['nombre' => 'Arismendi', 'estado_id' => 17],
            ['nombre' => 'Díaz', 'estado_id' => 17],
            ['nombre' => 'García', 'estado_id' => 17],
            ['nombre' => 'Gómez', 'estado_id' => 17],
            ['nombre' => 'Maneiro', 'estado_id' => 17],
            ['nombre' => 'Marcano', 'estado_id' => 17],
            ['nombre' => 'Mariño', 'estado_id' => 17],
            ['nombre' => 'Peninsula de Macanao', 'estado_id' => 17],
            ['nombre' => 'Tubores', 'estado_id' => 17],
            ['nombre' => 'Villalba', 'estado_id' => 17],

            // Portuguesa (estado_id = 18)
            ['nombre' => 'Agua Blanca', 'estado_id' => 18],
            ['nombre' => 'Araure', 'estado_id' => 18],
            ['nombre' => 'Esteller', 'estado_id' => 18],
            ['nombre' => 'Guanare', 'estado_id' => 18],
            ['nombre' => 'Guanarito', 'estado_id' => 18],
            ['nombre' => 'Monseñor José Vicente de Unda', 'estado_id' => 18],
            ['nombre' => 'Ospino', 'estado_id' => 18],
            ['nombre' => 'Páez', 'estado_id' => 18],
            ['nombre' => 'Papelón', 'estado_id' => 18],
            ['nombre' => 'San Genaro de Boconoíto', 'estado_id' => 18],
            ['nombre' => 'San Rafael de Onoto', 'estado_id' => 18],
            ['nombre' => 'Santa Rosalía', 'estado_id' => 18],
            ['nombre' => 'Sucre', 'estado_id' => 18],
            ['nombre' => 'Turén', 'estado_id' => 18],

            // Sucre (estado_id = 19)
            ['nombre' => 'Andrés Eloy Blanco', 'estado_id' => 19],
            ['nombre' => 'Andrés Mata', 'estado_id' => 19],
            ['nombre' => 'Arismendi', 'estado_id' => 19],
            ['nombre' => 'Benítez', 'estado_id' => 19],
            ['nombre' => 'Bermúdez', 'estado_id' => 19],
            ['nombre' => 'Bolívar', 'estado_id' => 19],
            ['nombre' => 'Cajigal', 'estado_id' => 19],
            ['nombre' => 'Cruz Salmerón Acosta', 'estado_id' => 19],
            ['nombre' => 'Libertador', 'estado_id' => 19],
            ['nombre' => 'Mariño', 'estado_id' => 19],
            ['nombre' => 'Mejía', 'estado_id' => 19],
            ['nombre' => 'Montes', 'estado_id' => 19],
            ['nombre' => 'Ribero', 'estado_id' => 19],
            ['nombre' => 'Sucre', 'estado_id' => 19],
            ['nombre' => 'Valdez', 'estado_id' => 19],



            // Táchira (estado_id = 20)
            ['nombre' => 'Andrés Bello', 'estado_id' => 20],
            ['nombre' => 'Antonio Rómulo Costa', 'estado_id' => 20],
            ['nombre' => 'Ayacucho', 'estado_id' => 20],
            ['nombre' => 'Bolívar', 'estado_id' => 20],
            ['nombre' => 'Cárdenas', 'estado_id' => 20],
            ['nombre' => 'Córdoba', 'estado_id' => 20],
            ['nombre' => 'Fernández Feo', 'estado_id' => 20],
            ['nombre' => 'Francisco de Miranda', 'estado_id' => 20],
            ['nombre' => 'García de Hevia', 'estado_id' => 20],
            ['nombre' => 'Guásimos', 'estado_id' => 20],
            ['nombre' => 'Independencia', 'estado_id' => 20],
            ['nombre' => 'Jáuregui', 'estado_id' => 20],
            ['nombre' => 'José María Vargas', 'estado_id' => 20],
            ['nombre' => 'Junín', 'estado_id' => 20],
            ['nombre' => 'Libertad', 'estado_id' => 20],
            ['nombre' => 'Libertador', 'estado_id' => 20],
            ['nombre' => 'Lobatera', 'estado_id' => 20],
            ['nombre' => 'Michelena', 'estado_id' => 20],
            ['nombre' => 'Panamericano', 'estado_id' => 20],
            ['nombre' => 'Pedro María Ureña', 'estado_id' => 20],
            ['nombre' => 'Rafael Urdaneta', 'estado_id' => 20],
            ['nombre' => 'Samuel Darío Maldonado', 'estado_id' => 20],
            ['nombre' => 'San Cristóbal', 'estado_id' => 20],
            ['nombre' => 'Seboruco', 'estado_id' => 20],
            ['nombre' => 'Simón Rodríguez', 'estado_id' => 20],
            ['nombre' => 'Sucre', 'estado_id' => 20],
            ['nombre' => 'Torbes', 'estado_id' => 20],
            ['nombre' => 'Uribante', 'estado_id' => 20],
            ['nombre' => 'San Judas Tadeo', 'estado_id' => 20],

            // Trujillo (estado_id = 21)
            ['nombre' => 'Andrés Bello', 'estado_id' => 21],
            ['nombre' => 'Boconó', 'estado_id' => 21],
            ['nombre' => 'Bolívar', 'estado_id' => 21],
            ['nombre' => 'Candelaria', 'estado_id' => 21],
            ['nombre' => 'Carache', 'estado_id' => 21],
            ['nombre' => 'Escuque', 'estado_id' => 21],
            ['nombre' => 'José Felipe Márquez Cañizales', 'estado_id' => 21],
            ['nombre' => 'Juan Vicente Campo Elías', 'estado_id' => 21],
            ['nombre' => 'La Ceiba', 'estado_id' => 21],
            ['nombre' => 'Miranda', 'estado_id' => 21],
            ['nombre' => 'Monte Carmelo', 'estado_id' => 21],
            ['nombre' => 'Motatán', 'estado_id' => 21],
            ['nombre' => 'Pampán', 'estado_id' => 21],
            ['nombre' => 'Pampanito', 'estado_id' => 21],
            ['nombre' => 'Rafael Rangel', 'estado_id' => 21],
            ['nombre' => 'San Rafael de Carvajal', 'estado_id' => 21],
            ['nombre' => 'Sucre', 'estado_id' => 21],
            ['nombre' => 'Trujillo', 'estado_id' => 21],
            ['nombre' => 'Urdaneta', 'estado_id' => 21],
            ['nombre' => 'Valera', 'estado_id' => 21],

            // La Guaira (estado_id = 22)
            ['nombre' => 'Vargas', 'estado_id' => 22],

            // Yaracuy (estado_id = 23)
            ['nombre' => 'Arístides Bastidas', 'estado_id' => 23],
            ['nombre' => 'Bolívar', 'estado_id' => 23],
            ['nombre' => 'Bruzual', 'estado_id' => 23],
            ['nombre' => 'Cocorote', 'estado_id' => 23],
            ['nombre' => 'Independencia', 'estado_id' => 23],
            ['nombre' => 'José Antonio Páez', 'estado_id' => 23],
            ['nombre' => 'La Trinidad', 'estado_id' => 23],
            ['nombre' => 'Manuel Monge', 'estado_id' => 23],
            ['nombre' => 'Nirgua', 'estado_id' => 23],
            ['nombre' => 'Peña', 'estado_id' => 23],
            ['nombre' => 'San Felipe', 'estado_id' => 23],
            ['nombre' => 'Sucre', 'estado_id' => 23],
            ['nombre' => 'Urachiche', 'estado_id' => 23],
            ['nombre' => 'Veroes', 'estado_id' => 23],

            // Zulia (estado_id = 24)
            ['nombre' => 'Almirante Padilla', 'estado_id' => 24],
            ['nombre' => 'Baralt', 'estado_id' => 24],
            ['nombre' => 'Cabimas', 'estado_id' => 24],
            ['nombre' => 'Catatumbo', 'estado_id' => 24],
            ['nombre' => 'Colón', 'estado_id' => 24],
            ['nombre' => 'Francisco Javier Pulgar', 'estado_id' => 24],
            ['nombre' => 'Guajira', 'estado_id' => 24],
            ['nombre' => 'Jesús Enrique Lossada', 'estado_id' => 24],
            ['nombre' => 'Jesús María Semprún', 'estado_id' => 24],
            ['nombre' => 'La Cañada de Urdaneta', 'estado_id' => 24],
            ['nombre' => 'Lagunillas', 'estado_id' => 24],
            ['nombre' => 'Machiques de Perijá', 'estado_id' => 24],
            ['nombre' => 'Mara', 'estado_id' => 24],
            ['nombre' => 'Maracaibo', 'estado_id' => 24],
            ['nombre' => 'Miranda', 'estado_id' => 24],
            ['nombre' => 'Rosario de Perijá', 'estado_id' => 24],
            ['nombre' => 'San Francisco', 'estado_id' => 24],
            ['nombre' => 'Santa Rita', 'estado_id' => 24],
            ['nombre' => 'Simón Bolívar', 'estado_id' => 24],
            ['nombre' => 'Sucre', 'estado_id' => 24],
            ['nombre' => 'Valmore Rodríguez', 'estado_id' => 24],


        ];

        Municipio::insert($municipios);
    }
}
